CREATE TABLE IF NOT EXISTS tasks (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     index_number INTEGER,
                                     created_at   DATE NOT NULL DEFAULT CURRENT_DATE,
                                     title        VARCHAR(255) NOT NULL,
    content      TEXT,
    status_id    BIGINT NOT NULL,
    assignee_id  BIGINT,
    CONSTRAINT fk_tasks_statuses
    FOREIGN KEY (status_id) REFERENCES task_statuses(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tasks_users
    FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE RESTRICT
    );

CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks(status_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id);
