CREATE TABLE IF NOT EXISTS labels (
                                      id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name       VARCHAR(1000) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_DATE
    );

